### ISSUE TITLE
I keep getting this error when run main.py

### ISSUE THREAD

**Issue by YomostXme** [codynhanpham/jp-to-en-ocr#1]
Traceback (most recent call last):
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Python311\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Python311\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program\jp-to-en-ocr\main.py", line 10, in <module>
    import utils
  File "E:\Program\jp-to-en-ocr\utils.py", line 12, in <module>
    manga_ocr = MangaOcr()
                ^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\manga_ocr\ocr.py", line 16, in __init__
    self.model = VisionEncoderDecoderModel.from_pretrained(pretrained_model_name_or_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\transformers\models\vision_encoder_decoder\modeling_vision_encoder_decoder.py", line 359, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\transformers\modeling_utils.py", line 3438, in from_pretrained
    elif has_file(pretrained_model_name_or_path, FLAX_WEIGHTS_NAME, **has_file_kwargs):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\transformers\utils\hub.py", line 614, in has_file
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=10)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\jp-to-en-ocr\venv\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by codynhanpham** [comment]
Hmmm seems like something with the internet connection, or something caused by other packages this repo depends on. Likely, the first time you ran the app it tried to download pre-trained models for OCR and translation from Hugging Face and failed.

Sounds silly, but you did have an internet connection, right?

Alright, this is the first issue so can you give me more info to debug? The more details, the better. Some questions I have in mind:
1. What's your OS?
2. Where did you get your Python installation? (From the [python.org](https://www.python.org/) site?)
3. Inside of `(venv)` (run the `venv-terminal.bat` file or `venv\Scripts\activate`), what is the output when you run `python -m ssl`?
4. How did you install the app? Were you using the `.bat` files and followed the steps or were you typing the commands in manually?
5. A little more sensitive, but what country are you running this code from? If I recall correctly, these American companies (Hugging Face, Google,...) do block connections from certain countries. Just to make sure you can connect to these sites.
6. To double-check, you also downloaded the `offline_models.zip` file and extracted it, right? And the complete folder should look like the attached image below.


I couldn't reproduce these errors, and they are all about connection errors so hopefully it's only something silly that needed to be ironed out.


The app folder should look like this:
![Screenshot 2024-02-18 094109](https://github.com/codynhanpham/jp-to-en-ocr/assets/87593612/a3244bb6-3c77-42ba-a7c9-83a35b60b80d)

**Comment by YomostXme** [comment]
Nvm, It's my connection problem. I think Hungging Face blocks my ip so i turn on VPN and now it works fine.
